CREATE TABLE google_users (id integer NOT NULL,
                           google_id varchar(255),
                           google_mail varchar(255),
                           PRIMARY KEY (id));
CREATE TABLE own_users (id integer NOT NULL,
                        verified boolean NOT NULL,
                        email varchar(255),
                        password_hash varchar(255),
                        PRIMARY KEY (id));
CREATE TABLE users (id integer GENERATED BY DEFAULT AS IDENTITY,
                    avatar_url varchar(255),
                    username varchar(255),
                    PRIMARY KEY (id));

CREATE TABLE verifications (
                            id UUID NOT NULL,
                            ttl integer NOT NULL,
                            user_id integer, created_at timestamp(6),
                            code varchar(255),
                            PRIMARY KEY (id));

ALTER TABLE IF EXISTS verifications ADD CONSTRAINT verifications_users_id_constraint
    FOREIGN KEY (user_id) REFERENCES own_users;

ALTER TABLE IF EXISTS google_users ADD CONSTRAINT google_users_id_constraint
    FOREIGN KEY (id) REFERENCES users;

ALTER TABLE IF EXISTS own_users ADD CONSTRAINT own_users_id_constraint
    FOREIGN KEY (id) REFERENCES users;