name: Deploy Backend to Yandex Cloud

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy"
        required: true
        default: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Login to Yandex Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v3
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      - name: Build, tag, and push image to Yandex Cloud Container Registry
        env:
          CR_REGISTRY: ${{ secrets.YA_REGISTRY }}
          CR_REPOSITORY: eventer-backend
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG .
          docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy on server
        run: |
          # Создаем временный файл для SSH-ключа
          echo "${{ secrets.SERVER_SSH_KEY }}" > ssh_key
          chmod 600 ssh_key
          
          # Выполняем SSH-подключение и передаем скрипт
          ssh -i ssh_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} /bin/bash << 'EOF'
            # Явно добавляем путь к yc в PATH
            export PATH=$PATH:/home/${{ secrets.SERVER_USER }}/yandex-cloud/bin
          
            # Получаем IAM-токен
            IAM_TOKEN=$(yc iam create-token)
          
            # Логинимся в Yandex Container Registry
            echo "$IAM_TOKEN" | docker login --username iam --password-stdin cr.yandex
          
            IMAGE="cr.yandex/${{ secrets.YA_REGISTRY }}/eventer-backend:${{ github.sha }}"
            CONTAINER_NAME=eventer-backend

            # Загружаем образ
            docker pull "$IMAGE"
          
            # Останавливаем и удаляем старый контейнер
            docker stop "$CONTAINER_NAME" || echo "No container to stop"
            docker rm "$CONTAINER_NAME" || echo "No container to remove"
          
            # Запускаем новый контейнер
            docker run -d --network eventer-net --env-file ~/backend/.env --name "$CONTAINER_NAME" --restart unless-stopped -p 8080:8080 "$IMAGE"
          
            # Проверяем статус контейнера
            docker ps -f name="$CONTAINER_NAME"
          
            # Очищаем старые образы
            docker image prune -f
          EOF
          
          # Удаляем временный файл с ключом
          rm -f ssh_key
